### ISSUE TITLE
existing examples

### ISSUE THREAD

**Issue by joeblew99** [chop-dbhi/nats-rpc#1]
I am also into this type of work.

there is prior atr here:
https://github.com/moul/protoc-gen-gotemplate

Have a look. LOts of examples

**Comment by bruth** [comment]
Hi @joeblew99 Do you mind providing a bit more context? Are you suggesting to use this library for doing the generation? Or are you just stating that you are interesting in an RPC layer for NATS?

**Comment by joeblew99** [comment]
both.

I like your approach, but i just wanted to help by also letting you know about moul's repo.

My goal is to be able to use protobuf to model data flows. Your RPC repo does some of that. 
Data flow architectures are kind of the next level up for Micro Services, because you can design them for parallel streaming computation. 
- add ability to choose the bus at gen time.  local bus versus network bus. 
- add annotations to manage  data level IO
- add diagraming so you can se whats happing :)

why data flow ?
- great for analytics
- materialised views for analytics. You can do ahead time analytics, so its real time and instant.
- DB becomes inconsequential to a high degree then.

**Comment by joeblew99** [comment]
https://github.com/chop-dbhi/origins

was looking good. Did you end up just using SQL for now ?

**Comment by bruth** [comment]
@joeblew99 I just pushed some changes based on what @savaki did using the proto generator/plugin hooks. It is certainly an improvement since it can read the service definition from the proto file directly and removes all the source parsing.

I did give up some of the command line options (not sure how to define them now that this uses protoc).

Origins was a fun project to work on. I am a bit sad I just stopped working on it. It was being modeled after Datomic because that database fascinates me, but is not open source so I wanted at least a basic alternative. However, my use case at the time was able to be solved with a different means without all the flexibility something like Datomic provides.

**Comment by joeblew99** [comment]
ok i see what you mean about parsing the protoc directly. nice. will have a play..

This might help you .... Its nice
https://github.com/fiorix/protoc-gen-cobra
- uses protobuf to generate cobra commands

Now i see what origins was i think that you will be really interested in data flow and materialised view based systems using protobuf and event streams ?

**Comment by bruth** [comment]
@joeblew99 Thanks for the suggestions. If you have specific feature ideas for the use cases you mentioned, I am happy to discuss them in individual issues.

**Comment by joeblew99** [comment]
@bruth How about if you post a roadmap ? i am working on many things that are similar to your work.
But i dont want to be pushy. Hence, if you post a roadmap and maybe some reasons for it and the intent i can also contribute then.
